### ISSUE TITLE
install is full with warnings

### ISSUE THREAD

**Issue by DrorTrieman** [orbs-network/orbs-client-sdk-javascript#6]
Are we ok with all of these warnings, including "no such file or directory"?
`
npm WARN npm npm does not support Node.js v10.10.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN saveError ENOENT: no such file or directory, open '/Users/drortrieman/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/drortrieman/package.json'
npm WARN drortrieman No description
npm WARN drortrieman No repository field.
npm WARN drortrieman No README data
npm WARN drortrieman No license field.

+ orbs-client-sdk@0.0.1
added 1 package in 4.956s
`

**Comment by bolshchikov** [comment]
the client-sdk requires support of BigInt which is provided starting from node 11, so the followinr warning are appropriate:
```bash
npm WARN npm npm does not support Node.js v10.10.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
```
The rest of them are related to the project that you are trying to install in.
